- hosts: workstation
  connection: local
  gather_facts: no
  pre_tasks:
    - name: Update apt-get repo and cache
      tags:
      - packages
      - maintenance
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Upgrade all apt packages
      tags: maintenance
      become: yes
      apt: upgrade=dist
  roles:
    - basic
